### ISSUE TITLE
Multiple Archival and Replication Location

### ISSUE THREAD

**Issue by mishrark1970** [marcus9467/rubrik#1]
Hi,

The script does not report on snapshots with multiple archival and replication locations, we are using cascading of locations and would appreciate, if all locations can be reported.

Thanks

Rajeev Mishra

**Comment by marcus9467** [comment]
Meant to update this sooner. Get-SnapshotDetails.ps1 can now support multiple archive locations per snapshot.

**Comment by mishrark1970** [comment]
Thanks a lot
